"use strict";

// correta:
// 0 = primeira alternativa
// 1 = segunda alternativa
// 2 = terceira alternativa
// 3 = quarta alternativa

const categorias = {
    solar: "☀️ ENERGIA SOLAR",
    vento: "🌬️ ENERGIA DO VENTO",
    agua: "💧 ÁGUA E ENERGIA",
    luz: "💡 LUZ",
    alimentos: "🍎 ENERGIA DOS ALIMENTOS",
    consumo: "🌱 USO CONSCIENTE",
    som: "🔊 SOM",
    baterias: "🔋 PILHAS E BATERIAS",
    calor: "🌡️ CALOR",
    biomassa: "🌿 ENERGIA DAS PLANTAS E RESÍDUOS",
    movimento: "⚽ MOVIMENTO",
    eletricidade: "⚡ ELETRICIDADE",
    mar: "🌊 ENERGIA DO MAR",
    fosseis: "⛽ COMBUSTÍVEIS",
    seguranca: "🤝 CUIDADOS NO DIA A DIA",
    geotermica: "🌍 CALOR DA TERRA"
};

// Monta o objeto de cada pergunta.
function criarPergunta(
    numero,
    tema,
    pergunta,
    alternativas,
    correta,
    explicacao
) {
    return {
        id: "facil_p" + String(numero).padStart(3, "0") + "_v1",
        tema,
        categoria: categorias[tema],
        pergunta,
        alternativas,
        correta,
        explicacao
    };
}

// Monta cada atividade de oito perguntas.
function criarBloco(modulo, numero, nome, perguntas) {
    return {
        atividadeId:
            "trilha_facil_m" + String(modulo).padStart(2, "0") +
            "_b" + String(numero).padStart(2, "0") + "_v1",
        nome,
        ordem: numero,
        perguntas
    };
}

const trilhaFacil = {
    nivel: "facil",
    nome: "Fácil",
    emoji: "🌱",
    versao: 1,
    xpPorAcerto: 10,
    modulos: []
};

// MÓDULO 1: Descobrindo a energia
trilhaFacil.modulos.push({
    id: "facil_m01_v1",
    nome: "Descobrindo a energia",
    ordem: 1,
    introducao: "Vamos descobrir energia na natureza, nos brinquedos e no nosso corpo.",
    blocos: [
        criarBloco(1, 1, "Primeiras descobertas", [
            criarPergunta(1, "solar",
                "De onde vem a energia solar?",
                ["Das ondas", "Do Sol", "Do vento", "Do carvão"],
                1, "A energia solar vem da luz do Sol."),
            criarPergunta(2, "vento",
                "O que empurra as pás de uma torre eólica?",
                ["A chuva", "O petróleo", "O vento", "A areia"],
                2, "O vento faz as pás girarem para ajudar a produzir eletricidade."),
            criarPergunta(3, "agua",
                "Qual fonte uma usina hidrelétrica aproveita?",
                ["A água em movimento", "O calor da areia", "A luz da Lua", "O carvão queimando"],
                0, "A água em movimento gira máquinas dentro da usina."),
            criarPergunta(4, "luz",
                "O que uma lanterna acesa nos ajuda a fazer?",
                ["Ouvir uma música", "Lavar a roupa", "Enxergar no escuro", "Esfriar a comida"],
                2, "A lanterna transforma parte da energia que recebe em luz."),
            criarPergunta(5, "alimentos",
                "De onde nosso corpo recebe energia para brincar?",
                ["Das tomadas", "Das pilhas", "Das lâmpadas", "Dos alimentos"],
                3, "Os alimentos fornecem energia para nosso corpo funcionar."),
            criarPergunta(6, "consumo",
                "A turma saiu da sala. O que fazer com a luz?",
                ["Acender mais luzes", "Deixar tudo aceso", "Acender uma luminária", "Apagar a luz"],
                3, "Uma sala vazia geralmente não precisa ficar iluminada."),
            criarPergunta(7, "som",
                "Qual objeto usamos para produzir música ao bater nele?",
                ["Tambor", "Caderno", "Pente", "Espelho"],
                0, "A batida faz o tambor vibrar e produzir som."),
            criarPergunta(8, "baterias",
                "O que guarda energia para um celular funcionar longe da tomada?",
                ["A capa", "A bateria", "A tela", "A câmera"],
                1, "A bateria armazena energia para alimentar o celular.")
        ]),

        criarBloco(1, 2, "Energia em ação", [
            criarPergunta(9, "calor",
                "O que um chuveiro elétrico aquece?",
                ["O espelho", "A toalha", "A água", "O sabonete"],
                2, "O chuveiro usa eletricidade para aquecer a água."),
            criarPergunta(10, "biomassa",
                "Qual destes materiais veio de uma planta?",
                ["Lata de alumínio", "Pedaço de plástico", "Pedaço de vidro", "Bagaço de cana"],
                3, "O bagaço sobra da cana e pode ser aproveitado em usinas."),
            criarPergunta(11, "movimento",
                "Qual destes objetos está em movimento?",
                ["Um copo na prateleira", "Um livro fechado na mesa", "Uma bola rolando", "Uma cadeira parada"],
                2, "A bola que rola muda de lugar e tem energia de movimento."),
            criarPergunta(12, "solar",
                "O que o Sol oferece para a Terra?",
                ["Luz e calor", "Pilhas e tomadas", "Vento e gasolina", "Carvão e fios"],
                0, "Recebemos do Sol luz e calor que fazem parte da nossa vida."),
            criarPergunta(13, "eletricidade",
                "Qual aparelho usa eletricidade para girar suas pás?",
                ["Bicicleta de pedal", "Ventilador", "Barco a vela", "Cata-vento de papel"],
                1, "O motor elétrico do ventilador faz suas pás girarem."),
            criarPergunta(14, "agua",
                "De onde vem a chuva que ajuda a encher os rios?",
                ["Das raízes", "Das nuvens", "Das pedras", "Das montanhas por dentro"],
                1, "A chuva cai das nuvens e ajuda a abastecer rios e lagos."),
            criarPergunta(15, "consumo",
                "A geladeira ficou aberta após o lanche. O que fazer?",
                ["Fechar a porta", "Acender a luz da cozinha", "Deixar aberta", "Abrir o congelador"],
                0, "Fechar a porta evita a entrada de mais calor na geladeira."),
            criarPergunta(16, "vento",
                "O vento é o quê?",
                ["Luz em movimento", "Água em movimento", "Areia parada", "Ar em movimento"],
                3, "Chamamos de vento o ar que se movimenta.")
        ]),

        criarBloco(1, 3, "Olhar e escutar", [
            criarPergunta(17, "luz",
                "Qual destes produz a própria luz quando está ligado?",
                ["Janela", "Espelho", "Abajur", "Mesa"],
                2, "A lâmpada do abajur produz luz quando recebe energia."),
            criarPergunta(18, "alimentos",
                "Uma criança está pedalando. Quem faz os pedais se moverem?",
                ["O som da campainha", "A cor da bicicleta", "O reflexo do espelho", "Os músculos da criança"],
                3, "Os músculos usam energia do corpo para fazer força nos pedais."),
            criarPergunta(19, "mar",
                "Qual movimento vemos na superfície do mar?",
                ["Raízes", "Chamas", "Fios", "Ondas"],
                3, "As ondas movimentam a água e sua energia pode ser aproveitada."),
            criarPergunta(20, "consumo",
                "Ninguém está assistindo à televisão. Qual atitude evita desperdício?",
                ["Desligar a televisão", "Acender outra tela", "Aumentar o volume", "Trocar o canal"],
                0, "Desligar a televisão quando ninguém assiste evita gasto desnecessário."),
            criarPergunta(21, "calor",
                "O que precisamos fornecer ao milho para fazer pipoca?",
                ["Vento frio", "Gelo", "Calor", "Sombra"],
                2, "O calor faz a água dentro do milho virar vapor e a pipoca estourar."),
            criarPergunta(22, "solar",
                "Uma placa solar que produz eletricidade aproveita o quê?",
                ["A luz do Sol", "O sal da chuva", "O barulho da rua", "O peso do telhado"],
                0, "Essa placa transforma parte da luz recebida em eletricidade."),
            criarPergunta(23, "som",
                "Que parte do corpo usamos para perceber os sons?",
                ["Os dedos dos pés", "Os ouvidos", "Os olhos", "Os joelhos"],
                1, "Os sons chegam aos nossos ouvidos e podemos escutá-los."),
            criarPergunta(24, "baterias",
                "Um carrinho a pilha parou porque a pilha acabou. O que faltou?",
                ["Luz para a pintura", "Energia para o motor", "Água para a carroceria", "Cor para as rodas"],
                1, "Sem energia disponível na pilha, o motor não consegue continuar funcionando.")
        ]),

        criarBloco(1, 4, "De onde vem?", [
            criarPergunta(25, "vento",
                "Qual destes pode mover um barco a vela?",
                ["Carvão", "Vento", "Gasolina", "Pilha"],
                1, "O vento empurra a vela e ajuda a movimentar o barco."),
            criarPergunta(26, "calor",
                "Uma pedrinha de gelo recebe calor. O que pode acontecer?",
                ["Ela se transformar em areia", "Ela virar madeira", "Ela aumentar de frio", "Ela derreter"],
                3, "Ao receber calor suficiente, o gelo vira água líquida."),
            criarPergunta(27, "biomassa",
                "Restos de alimentos podem gerar um gás em equipamentos especiais. Qual é ele?",
                ["Gás de um refrigerante", "Ar da sala", "Biogás", "Vapor de água"],
                2, "Em equipamentos próprios, seres muito pequenos decompõem restos e produzem biogás."),
            criarPergunta(28, "movimento",
                "O que faz um balanço começar a se mover?",
                ["Uma luz ao lado", "Um desenho no banco", "Uma mudança de cor", "Um empurrão"],
                3, "O empurrão transfere energia para o movimento do balanço."),
            criarPergunta(29, "agua",
                "Em uma usina hidrelétrica, a água faz uma roda especial girar. Como ela se chama?",
                ["Lâmpada", "Turbina", "Bateria", "Painel solar"],
                1, "A turbina gira com a passagem da água e ajuda o gerador a funcionar."),
            criarPergunta(30, "eletricidade",
                "Qual destes costuma funcionar ligado na tomada?",
                ["Liquidificador", "Garrafa térmica", "Prato", "Colher"],
                0, "O liquidificador usa eletricidade para fazer seu motor girar."),
            criarPergunta(31, "consumo",
                "Um brinquedo elétrico ficou ligado após a brincadeira. O que fazer?",
                ["Escondê-lo ainda ligado", "Aumentar o som dele", "Desligá-lo", "Ligar outro brinquedo"],
                2, "Desligar o brinquedo evita gastar energia sem necessidade."),
            criarPergunta(32, "solar",
                "O que o calor do Sol ajuda a retirar da roupa molhada?",
                ["A água que pode evaporar", "A linha da costura", "A cor de todos os botões", "O tecido da roupa"],
                0, "O calor ajuda a água a passar para o ar, secando a roupa.")
        ]),

        criarBloco(1, 5, "Ligando as ideias", [
            criarPergunta(33, "alimentos",
                "O corpo também usa energia para qual destas tarefas?",
                ["Mover as nuvens", "Mudar a cor do céu", "Acender o poste da rua", "Respirar"],
                3, "Nosso corpo precisa de energia até para tarefas que acontecem sem pensarmos."),
            criarPergunta(34, "luz",
                "Qual destes deixa a luz passar com facilidade?",
                ["Vidro transparente", "Porta de madeira", "Tampa de metal", "Parede de tijolos"],
                0, "A luz consegue atravessar o vidro transparente."),
            criarPergunta(35, "vento",
                "Uma bandeira está se mexendo ao ar livre. O que pode estar empurrando o tecido?",
                ["O peso da tinta", "O vento", "O calor do mastro", "A luz da bandeira"],
                1, "O ar em movimento empurra o tecido da bandeira."),
            criarPergunta(36, "baterias",
                "Uma pilha é uma pequena reserva de quê?",
                ["Vento para soprar", "Comida para pessoas", "Energia", "Água para beber"],
                2, "A pilha guarda energia que pode ser transformada em eletricidade."),
            criarPergunta(37, "calor",
                "Qual destes ajuda a manter a sopa quente por mais tempo?",
                ["Garrafa térmica", "Copo sem tampa ao vento", "Peneira aberta", "Prato cheio de gelo"],
                0, "A garrafa térmica dificulta a saída do calor."),
            criarPergunta(38, "agua",
                "Uma longa falta de chuva pode deixar um rio com quê?",
                ["Água sobrando sempre", "Menos água", "Uma cheia a cada manhã", "Mais água a cada tarde"],
                1, "Sem chuva por bastante tempo, a quantidade de água de um rio pode diminuir."),
            criarPergunta(39, "movimento",
                "Qual destes se move com a força dos pés, sem motor?",
                ["Barco a motor", "Carro a gasolina", "Bicicleta comum", "Trem elétrico"],
                2, "Ao pedalar, a pessoa usa a energia do corpo para mover a bicicleta."),
            criarPergunta(40, "consumo",
                "Qual passeio curto pode ser feito usando a energia do corpo?",
                ["Viagem de ônibus a diesel", "Volta de carro a gasolina", "Passeio de moto", "Caminhada com um responsável"],
                3, "Na caminhada, nossos músculos fazem o movimento usando energia dos alimentos.")
        ])
    ]
});

// MÓDULO 2: Energia em casa e na escola
trilhaFacil.modulos.push({
    id: "facil_m02_v1",
    nome: "Energia em casa e na escola",
    ordem: 2,
    introducao: "Vamos observar os aparelhos e aprender jeitos de usar melhor a energia.",
    blocos: [
        criarBloco(2, 1, "Uma casa cheia de energia", [
            criarPergunta(41, "baterias",
                "Para que serve o carregador de um celular?",
                ["Aumentar o tamanho da tela", "Trocar a cor da capa", "Guardar fotografias", "Repor energia na bateria"],
                3, "O carregador fornece energia para recarregar a bateria."),
            criarPergunta(42, "calor",
                "Qual aparelho usa calor para assar um bolo?",
                ["Rádio", "Forno", "Geladeira", "Ventilador"],
                1, "O forno transfere calor para a massa e ajuda o bolo a assar."),
            criarPergunta(43, "solar",
                "Uma sombra cobre a placa solar. O que chega menos à placa?",
                ["Água da chuva", "Som dos pássaros", "Luz do Sol", "Vento da rua"],
                2, "A sombra bloqueia parte da luz que a placa poderia aproveitar."),
            criarPergunta(44, "movimento",
                "O elevador usa um motor para fazer o quê?",
                ["Mover a cabine", "Criar o prédio", "Lavar o chão", "Pintar a porta"],
                0, "O motor transforma energia para movimentar a cabine do elevador."),
            criarPergunta(45, "agua",
                "O que uma usina hidrelétrica fornece para as casas?",
                ["Lenha", "Pilhas prontas", "Eletricidade", "Gasolina"],
                2, "A usina transforma parte da energia da água em eletricidade."),
            criarPergunta(46, "consumo",
                "O quarto está escuro, mas lá fora há Sol. O que pode ajudar sem acender lâmpadas?",
                ["Acender a televisão", "Fechar a janela com madeira", "Cobrir a janela com papel", "Abrir a cortina"],
                3, "Abrir a cortina deixa a luz natural entrar."),
            criarPergunta(47, "vento",
                "O que mantém uma pipa comum no ar quando ela está voando?",
                ["O calor da tinta", "A força do vento", "O barulho da linha", "Uma bateria escondida"],
                1, "O vento empurra a pipa e ajuda a sustentá-la no ar."),
            criarPergunta(48, "biomassa",
                "A cana pode virar um combustível chamado etanol. Onde ele pode ser usado?",
                ["Em carros preparados para ele", "Em uma lanterna a pilha", "Em um cata-vento de papel", "Em um painel solar"],
                0, "O etanol é um combustível de origem vegetal usado em alguns veículos.")
        ]),

        criarBloco(2, 2, "Aprender com a rotina", [
            criarPergunta(49, "eletricidade",
                "Uma máquina de lavar ligada usa energia para quê?",
                ["Fabricar tecido", "Produzir sabão", "Cultivar algodão", "Girar e lavar as roupas"],
                3, "A máquina usa eletricidade para movimentar a roupa e realizar a lavagem."),
            criarPergunta(50, "som",
                "Uma campainha toca. Qual sinal ela produz para avisar alguém?",
                ["Cheiro", "Som", "Sombra", "Sabor"],
                1, "A campainha transforma parte da energia recebida em som."),
            criarPergunta(51, "fosseis",
                "Qual destes é um combustível vendido em postos?",
                ["Vento", "Água da chuva", "Gasolina", "Luz do Sol"],
                2, "A gasolina é um combustível usado por muitos veículos."),
            criarPergunta(52, "luz",
                "Um espelho comum brilha quando recebe luz. O que ele faz?",
                ["Guarda o vento", "Transforma som em luz", "Fabrica luz sozinho", "Reflete a luz recebida"],
                3, "O espelho devolve parte da luz que chega até ele."),
            criarPergunta(53, "consumo",
                "A aula no computador terminou. O que a turma pode fazer?",
                ["Seguir a orientação para desligá-lo", "Ligar todos os computadores vazios", "Deixar um vídeo rodando sem assistir", "Aumentar o brilho de todas as telas"],
                0, "Desligar equipamentos quando não serão usados evita desperdício de energia."),
            criarPergunta(54, "mar",
                "Uma máquina aproveita o sobe e desce das ondas. Ela usa energia de onde?",
                ["Do mar", "Do Sol diretamente", "Do carvão", "De uma pilha comum"],
                0, "A máquina aproveita o movimento das ondas do mar."),
            criarPergunta(55, "solar",
                "Um aquecedor solar recebe luz do Sol. O que ele pode aquecer?",
                ["O vento da cidade", "A bateria do controle remoto", "A água do banho", "O combustível do carro"],
                2, "O aquecedor solar aproveita o Sol para aquecer água."),
            criarPergunta(56, "alimentos",
                "Qual destes pode fornecer energia ao nosso corpo quando comemos?",
                ["Papel", "Arroz", "Vidro", "Areia"],
                1, "O arroz é um alimento que fornece energia para o corpo.")
        ]),

        criarBloco(2, 3, "Pequenas escolhas", [
            criarPergunta(57, "vento",
                "Onde uma torre eólica precisa ficar para aproveitar o vento?",
                ["Dentro de um armário", "Em um quarto fechado", "Em um local com vento adequado", "Dentro de um túnel sem vento"],
                2, "O vento precisa alcançar as pás para movimentá-las."),
            criarPergunta(58, "calor",
                "Para manter os alimentos frios, a geladeira retira deles o quê?",
                ["Calor", "Nome", "Tamanho", "Cor"],
                0, "A geladeira usa energia para retirar calor de seu interior."),
            criarPergunta(59, "baterias",
                "Qual destes pode usar pilhas para funcionar?",
                ["Régua de plástico", "Controle remoto", "Colher de madeira", "Caderno de desenho"],
                1, "As pilhas fornecem energia para os componentes do controle remoto."),
            criarPergunta(60, "biomassa",
                "Qual sobra de uma plantação pode ser aproveitada para produzir energia?",
                ["Caco de vidro", "Tampa de metal", "Palha de milho", "Saquinho de plástico"],
                2, "A palha de milho é um material vegetal que pode fornecer energia."),
            criarPergunta(61, "agua",
                "Uma represa guarda água. Como chamamos o lugar onde ela fica armazenada?",
                ["Reservatório", "Bateria", "Painel solar", "Tomada"],
                0, "O reservatório guarda água, que pode ser usada pela usina."),
            criarPergunta(62, "consumo",
                "Duas lâmpadas iluminam igual. Qual escolha economiza energia?",
                ["A que tem a caixa maior", "A que gasta menos energia", "A que gasta mais energia", "A que tem a embalagem mais colorida"],
                1, "Para a mesma iluminação, gastar menos energia é uma escolha eficiente."),
            criarPergunta(63, "movimento",
                "Para um patinete sem motor andar, a criança faz o quê?",
                ["Liga um carregador", "Acende uma lâmpada", "Coloca gasolina nele", "Empurra o chão com o pé"],
                3, "O impulso do pé ajuda a movimentar o patinete."),
            criarPergunta(64, "luz",
                "O que aparece atrás de um objeto que bloqueia a luz?",
                ["Gelo", "Chama", "Vento", "Sombra"],
                3, "A sombra aparece onde a luz foi bloqueada pelo objeto.")
        ]),

        criarBloco(2, 4, "Cada coisa tem seu jeito", [
            criarPergunta(65, "fosseis",
                "O petróleo é encontrado em rochas no subsolo. Onde fica o subsolo?",
                ["Acima das estrelas", "Debaixo da superfície do chão", "Na copa das árvores", "Dentro das nuvens"],
                1, "O subsolo fica abaixo da superfície onde caminhamos."),
            criarPergunta(66, "eletricidade",
                "Qual destes precisa de eletricidade para mostrar desenhos na tela?",
                ["Tablet", "Cartaz pintado", "Livro de papel", "Caderno"],
                0, "O tablet usa energia elétrica para fazer a tela e os componentes funcionarem."),
            criarPergunta(67, "calor",
                "A garrafa tem água quente. Para onde o calor tende a passar?",
                ["Só para dentro da água", "Para lugar nenhum", "Para lugares mais frios ao redor", "Só para lugares mais quentes"],
                2, "O calor passa de algo mais quente para algo mais frio."),
            criarPergunta(68, "vento",
                "Ao soprar um cata-vento de papel, o que você movimenta?",
                ["A luz", "O ar", "O chão", "O calor do Sol"],
                1, "O sopro movimenta o ar, que pode empurrar as pás do cata-vento."),
            criarPergunta(69, "solar",
                "Qual lugar recebe luz do Sol diretamente em um dia claro?",
                ["Uma gaveta fechada", "Uma caixa fechada", "Um quarto sem janela", "Um telhado descoberto"],
                3, "Um telhado sem cobertura por cima pode receber diretamente a luz do Sol."),
            criarPergunta(70, "agua",
                "O chuveiro elétrico está ligado durante um banho. Ele usa quais recursos?",
                ["Gasolina e vento", "Lenha e areia", "Petróleo e pilhas", "Água e eletricidade"],
                3, "O banho usa água, e o chuveiro usa eletricidade para aquecê-la."),
            criarPergunta(71, "baterias",
                "Uma lanterna recarregável ficou sem energia. O que um adulto pode fazer?",
                ["Encher a lanterna de água", "Pintar a lanterna de amarelo", "Recarregar a bateria do jeito indicado", "Deixar a lanterna no congelador"],
                2, "Uma bateria recarregável pode receber energia novamente com o carregador adequado."),
            criarPergunta(72, "consumo",
                "Qual hábito ajuda a gastar menos água e energia no banho quente?",
                ["Evitar ficar mais tempo que o necessário", "Deixar o chuveiro ligado após sair", "Tomar outro banho logo em seguida sem motivo", "Aumentar o tempo de banho sem precisar"],
                0, "Banhos sem demora desnecessária reduzem o uso de água e de energia.")
        ]),

        criarBloco(2, 5, "Cuidar e aproveitar", [
            criarPergunta(73, "movimento",
                "Um brinquedo de corda funciona depois que sua mola é enrolada. Onde ficou guardada a energia?",
                ["Na mola", "Na pintura", "No nome do brinquedo", "Na caixa vazia"],
                0, "A mola deformada guarda energia e a libera para mover o brinquedo."),
            criarPergunta(74, "som",
                "Quando a caixa de som toca música, o que ouvimos?",
                ["O vento virando gelo", "A cor saindo da tela", "Vibrações que chegam como som", "A luz se transformando em água"],
                2, "O alto-falante vibra e faz o som se espalhar pelo ar."),
            criarPergunta(75, "seguranca",
                "Uma pilha usada precisa ser descartada. O que a criança deve fazer?",
                ["Abrir a pilha para ver por dentro", "Enterrá-la no jardim", "Entregá-la a um responsável para coleta adequada", "Jogá-la no rio"],
                2, "Um responsável pode levar a pilha a um ponto de coleta adequado."),
            criarPergunta(76, "mar",
                "A água do mar sobe e desce ao longo do dia. Como chamamos isso?",
                ["Vento", "Fumaça", "Chuva", "Maré"],
                3, "A maré é a mudança do nível da água do mar e pode ser aproveitada para gerar energia."),
            criarPergunta(77, "eletricidade",
                "Um ônibus elétrico anda usando qual forma de energia no motor?",
                ["Sonora diretamente", "Luminosa diretamente", "Calor do asfalto diretamente", "Elétrica"],
                3, "O motor do ônibus elétrico usa eletricidade para produzir movimento."),
            criarPergunta(78, "biomassa",
                "Em uma usina, o bagaço de cana é aproveitado como combustível. O que ele libera ao queimar?",
                ["Vento frio", "Calor", "Água potável", "Gelo"],
                1, "A queima do bagaço libera calor que pode ser usado pela usina."),
            criarPergunta(79, "solar",
                "À noite, uma placa solar deixa de receber diretamente o quê?",
                ["A água da chuva", "A luz do Sol", "Os sons da cidade", "O ar da rua"],
                1, "Sem a luz do Sol, a placa não gera eletricidade a partir dessa luz."),
            criarPergunta(80, "consumo",
                "O ventilador está ligado em uma sala vazia. Qual escolha evita gasto desnecessário?",
                ["Desligá-lo", "Acender uma lâmpada ao lado", "Aumentar a velocidade", "Ligar outro ventilador"],
                0, "Sem alguém para aproveitar o vento, manter o ventilador ligado pode desperdiçar energia.")
        ])
    ]
});

// MÓDULO 3: A natureza também ajuda
trilhaFacil.modulos.push({
    id: "facil_m03_v1",
    nome: "A natureza também ajuda",
    ordem: 3,
    introducao: "Sol, vento, água e plantas podem fornecer energia. Vamos conhecer essas fontes.",
    blocos: [
        criarBloco(3, 1, "Fontes para descobrir", [
            criarPergunta(81, "solar",
                "As plantas usam a luz do Sol para fabricar o quê?",
                ["Gasolina pronta", "Vidro", "Seu próprio alimento", "Fios de cobre"],
                2, "Com luz, água e gás do ar, as plantas produzem seu alimento."),
            criarPergunta(82, "vento",
                "Um parque eólico tem várias torres. O que costuma girar nelas?",
                ["As pás", "As bases", "As portas", "Os fios"],
                0, "O vento movimenta as pás ligadas aos equipamentos das torres."),
            criarPergunta(83, "agua",
                "A água aquecida pelo Sol pode evaporar. Para onde ela vai?",
                ["Para dentro das pedras, como metal", "Para as plantas, como vidro", "Para o céu, como areia", "Para o ar, como vapor"],
                3, "Na evaporação, a água passa para o ar em forma de vapor."),
            criarPergunta(84, "biomassa",
                "Biomassa pode vir de plantas. Qual destes é um exemplo?",
                ["Pedra", "Madeira", "Lata de refrigerante", "Garrafa de vidro"],
                1, "A madeira veio de uma árvore e é um exemplo de biomassa."),
            criarPergunta(85, "geotermica",
                "Dentro da Terra existe muito calor. Essa energia vem de onde?",
                ["Das pilhas usadas", "Da luz dos postes", "Do interior do planeta", "Do barulho dos carros"],
                2, "A energia chamada geotérmica aproveita o calor do interior da Terra."),
            criarPergunta(86, "fosseis",
                "O carvão mineral demora muito para se formar. Ele é reposto pela natureza em poucos dias?",
                ["Sim, a cada amanhecer", "Não, sua formação leva muito tempo", "Sim, quando venta", "Sim, a cada chuva"],
                1, "O carvão mineral se forma em um tempo muito maior que o de uma vida humana."),
            criarPergunta(87, "consumo",
                "Por que vale a pena cuidar dos brinquedos para durarem mais?",
                ["Para evitar fabricar tantos brinquedos novos", "Para gastar mais pilhas", "Para trocar todos a cada semana", "Para aumentar o uso de embalagens"],
                0, "Fabricar brinquedos novos exige materiais e energia."),
            criarPergunta(88, "mar",
                "Qual destes pode aproveitar a energia das ondas?",
                ["Uma pilha dentro de um armário", "Uma placa solar dentro de uma gaveta", "Um fogão desligado", "Um equipamento próprio instalado no mar"],
                3, "Equipamentos especiais conseguem transformar o movimento das ondas em eletricidade.")
        ]),

        criarBloco(3, 2, "Natureza em movimento", [
            criarPergunta(89, "vento",
                "Pás de uma torre eólica precisam de combustível queimando para aproveitar o vento?",
                ["Sim, precisam queimar gasolina nas pás", "Sim, precisam queimar lenha nas pás", "Não, elas aproveitam o vento", "Sim, precisam queimar carvão nas pás"],
                2, "O vento fornece o movimento que a torre aproveita para gerar eletricidade."),
            criarPergunta(90, "agua",
                "Ao construir uma usina perto de um rio, quem também precisa de cuidados?",
                ["Somente quem desenha placas", "Peixes, plantas e pessoas do lugar", "Somente quem conta carros", "Somente quem vende tinta"],
                1, "Usinas podem mudar o ambiente e precisam considerar a vida ao redor."),
            criarPergunta(91, "solar",
                "Qual tecnologia pode produzir eletricidade sem partes girando?",
                ["Torre eólica com pás", "Gerador movido por um motor", "Turbina movida a água", "Placa solar"],
                3, "A placa solar produz eletricidade a partir da luz, sem precisar girar."),
            criarPergunta(92, "alimentos",
                "Um cavalo usa energia para correr. De onde vem essa energia?",
                ["Dos alimentos que ele come", "Do som dos cascos", "Da cor do pelo", "Das ferraduras"],
                0, "Assim como nós, os animais recebem energia dos alimentos."),
            criarPergunta(93, "biomassa",
                "Uma usina pode aproveitar cascas de arroz. Qual sobra ela está usando?",
                ["Uma sobra de vidro", "Uma sobra de metal", "Uma sobra de plantas", "Uma sobra de plástico"],
                2, "Cascas de arroz são materiais vegetais que podem ter aproveitamento energético."),
            criarPergunta(94, "luz",
                "Durante o dia, qual fonte ilumina naturalmente uma floresta?",
                ["O carvão", "O Sol", "A gasolina", "Uma bateria enterrada"],
                1, "A luz do Sol chega à floresta e ajuda as plantas a viver."),
            criarPergunta(95, "consumo",
                "Usar os dois lados de uma folha ajuda a economizar o quê?",
                ["Papel e recursos para produzi-lo", "Movimento do vento", "Luz do Sol", "Som da sala"],
                0, "Produzir papel usa materiais, água e energia; aproveitar a folha evita desperdício."),
            criarPergunta(96, "movimento",
                "Um rio corre e o vento sopra. O que os dois têm em comum?",
                ["Ficam sempre parados", "São feitos de fogo", "Dependem de pilhas", "Estão em movimento"],
                3, "Tanto a água do rio quanto o ar do vento podem carregar energia de movimento.")
        ]),

        criarBloco(3, 3, "Uma viagem pelas fontes", [
            criarPergunta(97, "fosseis",
                "A gasolina é fabricada a partir de qual recurso?",
                ["Vento", "Luz do Sol", "Água da chuva", "Petróleo"],
                3, "A gasolina é um dos produtos obtidos do petróleo."),
            criarPergunta(98, "agua",
                "Qual destes pode mostrar água descendo e se movimentando na natureza?",
                ["Cachoeira", "Água em um copo", "Poça parada", "Lago sem corrente aparente"],
                0, "Na cachoeira, vemos a água descer e se mover."),
            criarPergunta(99, "vento",
                "Algumas torres eólicas ficam no mar. Qual fonte elas aproveitam?",
                ["Areia do fundo", "Sal da água", "Vento sobre o mar", "Barulho dos peixes"],
                2, "Mesmo instaladas no mar, as torres eólicas aproveitam o vento."),
            criarPergunta(100, "geotermica",
                "Uma fonte natural pode ter água aquecida pelo interior da Terra. Qual energia a aquece?",
                ["Movimento de uma bicicleta", "Calor da Terra", "Som das árvores", "Luz de uma televisão"],
                1, "Em certos lugares, o calor do interior da Terra aquece águas subterrâneas."),
            criarPergunta(101, "biomassa",
                "Qual destes restos pode servir à produção de biogás em equipamentos adequados?",
                ["Cacos de vidro", "Latinhas vazias", "Restos de frutas", "Pedaços de ferro"],
                2, "Restos de frutas podem ser decompostos em equipamentos que aproveitam o gás produzido."),
            criarPergunta(102, "eletricidade",
                "Depois de ser produzida na usina, a eletricidade chega às cidades por quê?",
                ["Canais de areia", "Redes de fios e equipamentos", "Caminhões cheios de água", "Sacos de folhas"],
                1, "As redes elétricas levam energia das usinas até os lugares de uso."),
            criarPergunta(103, "solar",
                "É preciso queimar o Sol dentro de uma placa solar?",
                ["Sim, com carvão dentro da placa", "Sim, com lenha sobre a placa", "Sim, com gasolina sobre a placa", "Não, a placa recebe sua luz"],
                3, "A placa solar aproveita a luz que chega do Sol, sem queimar combustível."),
            criarPergunta(104, "consumo",
                "Separar materiais para reciclagem pode ajudar a quê?",
                ["Reaproveitar materiais e poupar recursos", "Impedir o uso de materiais novamente", "Aumentar compras sem necessidade", "Fazer mais lixo ir para os rios"],
                0, "Reciclar pode reduzir o uso de matérias-primas e de energia na fabricação.")
        ]),

        criarBloco(3, 4, "Recursos ao nosso redor", [
            criarPergunta(105, "agua",
                "Uma roda recebe água de um lado e gira. O que a água transferiu para a roda?",
                ["Cheiro de chuva", "Cor azul", "Sabor de sal", "Energia de movimento"],
                3, "A força da água faz a roda girar e transfere energia para ela."),
            criarPergunta(106, "solar",
                "Qual destes pode aproveitar calor do Sol para preparar comida?",
                ["Rádio a pilha", "Geladeira desligada", "Forno solar", "Ventilador de teto"],
                2, "Um forno solar aproveita o Sol para aquecer alimentos; seu uso é feito por adultos."),
            criarPergunta(107, "som",
                "Qual movimento produz o som de um violão?",
                ["O peso do estojo", "A cor da madeira", "O brilho da tinta", "A vibração das cordas"],
                3, "As cordas vibram e essas vibrações produzem som."),
            criarPergunta(108, "biomassa",
                "Depois de colher cana, o que ajuda a ter novas plantas no futuro?",
                ["Esperar a gasolina virar cana", "Plantar e cuidar de novas canas", "Jogar plástico no solo", "Retirar toda a terra"],
                1, "Cultivar novas plantas faz parte do cuidado necessário ao usar recursos vegetais."),
            criarPergunta(109, "movimento",
                "Qual objeto pode aproveitar água corrente para girar?",
                ["Espelho", "Painel solar", "Roda-d'água", "Pilha comum"],
                2, "A água corrente empurra a roda-d'água e faz a roda girar."),
            criarPergunta(110, "vento",
                "Por que o vento não é vendido dentro de um tanque de gasolina?",
                ["Porque é uma pedra enterrada", "Porque é ar em movimento", "Porque é um líquido escuro", "Porque é um fio elétrico"],
                1, "O vento é uma fonte natural diferente dos combustíveis guardados em tanques."),
            criarPergunta(111, "consumo",
                "Uma garrafa reutilizável pode diminuir a necessidade de quê?",
                ["Fabricar tantas garrafas descartáveis", "Usar água para beber", "Ouvir os sons da escola", "Receber luz do Sol"],
                0, "Reutilizar a garrafa evita parte dos materiais e da energia de novas embalagens."),
            criarPergunta(112, "fosseis",
                "O carvão que sai de minas é chamado de quê?",
                ["Carvão mineral", "Carvão eólico", "Carvão solar", "Carvão de bateria"],
                0, "O carvão mineral é retirado de depósitos no subsolo.")
        ]),

        criarBloco(3, 5, "Juntando as descobertas", [
            criarPergunta(113, "baterias",
                "Uma casa guardou energia solar em uma bateria. Quando essa reserva pode ajudar?",
                ["Só se a casa for pintada", "Quando falta luz do Sol", "Só enquanto a bateria está vazia", "Só se o Sol ficar mais perto"],
                1, "A energia guardada pode ser usada em outro momento, dentro da capacidade da bateria."),
            criarPergunta(114, "agua",
                "A chuva pode ajudar uma usina hidrelétrica porque faz o quê?",
                ["Fabrica fios de metal", "Enche as pás de gasolina", "Ajuda a repor a água dos rios", "Acende sozinha todas as lâmpadas"],
                2, "A chuva contribui para a água disponível nos rios e reservatórios."),
            criarPergunta(115, "vento",
                "Se o vento fica fraco, uma torre eólica pode produzir o quê?",
                ["Mais lenha", "Mais carvão", "Mais gasolina", "Menos eletricidade"],
                3, "Com pouco vento adequado, a torre pode produzir menos eletricidade."),
            criarPergunta(116, "calor",
                "Qual destes pode aquecer uma pedra durante o dia?",
                ["Luz do Sol", "Ar frio", "Sombra constante", "Água gelada"],
                0, "Ao receber luz do Sol, a pedra pode ficar mais quente."),
            criarPergunta(117, "biomassa",
                "Queimar madeira libera energia. Qual cuidado com as árvores faz sentido?",
                ["Queimar toda a floresta", "Cortar árvores sem limite", "Cuidar das florestas e usar madeira de origem adequada", "Retirar todas as plantas do lugar"],
                2, "O uso da madeira precisa respeitar a origem do material e a preservação das florestas."),
            criarPergunta(118, "mar",
                "A energia das ondas é aproveitada a partir de qual movimento?",
                ["Da sombra das conchas", "Do sobe e desce da água", "Da cor dos barcos", "Do brilho da areia"],
                1, "O movimento da água transfere energia para equipamentos próprios."),
            criarPergunta(119, "solar",
                "Uma nuvem grossa cobre o Sol. O que pode acontecer com uma placa solar?",
                ["Virar uma bateria nova", "Começar a queimar carvão", "Produzir gasolina", "Produzir menos eletricidade"],
                3, "Nuvens podem reduzir a luz que chega à placa e diminuir sua produção."),
            criarPergunta(120, "eletricidade",
                "Uma casa usa energia solar e outra usa energia do vento. Ambas podem acender o quê?",
                ["Uma lâmpada elétrica", "Uma pedra sem lâmpada", "Um papel sem aparelho", "Uma colher sem aparelho"],
                0, "Fontes diferentes podem ser transformadas em eletricidade para os mesmos usos.")
        ])
    ]
});

// MÓDULO 4: Brincando de cientista
trilhaFacil.modulos.push({
    id: "facil_m04_v1",
    nome: "Brincando de cientista",
    ordem: 4,
    introducao: "Vamos pensar no que acontece com a luz, o som, o calor e os movimentos.",
    blocos: [
        criarBloco(4, 1, "O que aconteceu?", [
            criarPergunta(121, "movimento",
                "Uma bola parada recebe um chute. O que pode acontecer?",
                ["A bola se transformar em gelo", "A bola virar uma lâmpada", "A bola começar a rolar", "A bola produzir gasolina"],
                2, "O chute transfere energia do corpo para o movimento da bola."),
            criarPergunta(122, "luz",
                "Ao apagar a lanterna em um quarto escuro, o que desaparece?",
                ["As paredes", "Os sons de fora", "O ar do quarto", "A luz que ela emitia"],
                3, "A lanterna deixa de produzir luz quando é desligada."),
            criarPergunta(123, "vento",
                "Qual brinquedo mostra facilmente o vento fazendo algo girar?",
                ["Cata-vento", "Dominó", "Quebra-cabeça", "Boneco de pano parado"],
                0, "O cata-vento gira quando o ar empurra suas pás."),
            criarPergunta(124, "calor",
                "Ao esfregar as mãos uma na outra, elas podem ficar como?",
                ["Feitas de gelo", "Mais quentes", "Transparentes", "Molhadas de chuva"],
                1, "O atrito entre as mãos pode transformar parte do movimento em calor."),
            criarPergunta(125, "agua",
                "Uma torneira enche um copo. Quando fechamos a torneira, o que para?",
                ["O som de todas as coisas", "O vento de fora", "A luz do Sol", "A entrada de água pelo cano"],
                3, "Fechar a torneira interrompe a passagem de água por ela."),
            criarPergunta(126, "som",
                "Um sino toca depois de ser atingido. O que está vibrando?",
                ["A sombra do sino", "O sino", "O nome do sino", "A cor do sino"],
                1, "A vibração do sino faz o ar vibrar e produz som."),
            criarPergunta(127, "solar",
                "Duas toalhas iguais estão molhadas. Uma recebe Sol, outra fica à sombra. Qual recebe mais luz solar direta?",
                ["A toalha ao Sol", "A toalha à sombra", "As duas recebem luz direta igual", "Nenhuma pode receber luz"],
                0, "A toalha ao Sol recebe diretamente a luz que a sombra bloqueia."),
            criarPergunta(128, "baterias",
                "Uma lanterna pode acender sem fio ligado à parede. O que explica isso?",
                ["Ela usa a cor da parede", "Ela usa o nome da marca", "Ela usa energia de pilhas ou bateria", "Ela usa a sombra da mão"],
                2, "Pilhas e baterias podem fornecer energia sem ligação contínua à tomada.")
        ]),

        criarBloco(4, 2, "Observar e comparar", [
            criarPergunta(129, "eletricidade",
                "O interruptor de uma luminária serve para quê?",
                ["Mudar o vento da rua", "Ligar ou desligar a luz", "Encher uma caixa-d'água", "Carregar o celular"],
                1, "O interruptor controla a passagem de eletricidade que permite acender a lâmpada."),
            criarPergunta(130, "movimento",
                "Um carrinho desce uma rampa. Para qual direção ele vai nessa descida?",
                ["Para dentro da parede", "Para a parte mais alta sem impulso", "Para a parte mais baixa", "Para o teto"],
                2, "A gravidade puxa o carrinho para baixo e ele ganha movimento na descida."),
            criarPergunta(131, "vento",
                "Uma folha de papel se move com um sopro. O que a empurrou?",
                ["O som da folha", "A luz do papel", "O ar do sopro", "A cor da mesa"],
                2, "O ar em movimento pode empurrar objetos leves."),
            criarPergunta(132, "luz",
                "Para fazer sombra em uma parede, o objeto precisa ficar onde?",
                ["Dentro de uma caixa fechada longe dali", "Entre a luz e a parede", "Atrás da parede", "Atrás da lanterna, fora do feixe"],
                1, "O objeto faz sombra quando bloqueia a luz no caminho até a parede."),
            criarPergunta(133, "calor",
                "Uma colher fria toca água morna. O calor passa primeiro de onde para onde?",
                ["Da cor da colher para o ar", "Do som da água para o copo", "Da colher fria para a água morna", "Da água morna para a colher"],
                3, "O calor passa do corpo mais quente para o mais frio."),
            criarPergunta(134, "consumo",
                "Qual ação permite desenhar durante o dia sem ligar uma luminária?",
                ["Usar um lugar com boa luz natural", "Cobrir todas as janelas", "Desenhar dentro de um armário fechado", "Escolher um canto escuro"],
                0, "Um local bem iluminado pelo dia pode dispensar uma lâmpada extra."),
            criarPergunta(135, "biomassa",
                "Por que uma casca de banana e um bagaço de cana são parecidos?",
                ["Os dois são vidros", "Os dois são metais", "Os dois são pedras", "Os dois vieram de plantas"],
                3, "Os dois são materiais de origem vegetal que podem ser reaproveitados de diferentes formas."),
            criarPergunta(136, "som",
                "Ao tocar um tambor mais forte, o som costuma ficar como?",
                ["Mais alto", "Sem nenhuma vibração", "Com mais luz", "Com mais sombra"],
                0, "Uma batida mais forte costuma produzir vibrações maiores e um som mais alto.")
        ]),

        criarBloco(4, 3, "Fazer perguntas", [
            criarPergunta(137, "solar",
                "O Sol aquece uma poça e parte da água evapora. A água virou o quê?",
                ["Areia", "Vapor de água", "Gasolina", "Pedra"],
                1, "A água evaporada continua sendo água, mas no estado de vapor."),
            criarPergunta(138, "movimento",
                "Um pião está rodando. Qual palavra descreve o que ele faz?",
                ["Evaporar", "Derreter", "Girar", "Congelar"],
                2, "O giro do pião é uma forma de movimento."),
            criarPergunta(139, "agua",
                "A água de um rio corre morro abaixo. O que ajuda nessa descida?",
                ["A cor das folhas", "O som dos pássaros", "A tinta das casas", "A gravidade"],
                3, "A gravidade puxa a água para partes mais baixas do terreno."),
            criarPergunta(140, "baterias",
                "Um brinquedo indica que usa pilhas recarregáveis. O que isso significa?",
                ["Elas funcionam só debaixo d'água", "Elas nunca ficam sem energia", "Elas criam energia sem receber nada", "Elas podem receber energia novamente"],
                3, "Pilhas recarregáveis podem voltar a armazenar energia usando o carregador adequado."),
            criarPergunta(141, "luz",
                "Qual destes bloqueia mais a luz de uma lanterna?",
                ["Uma placa de madeira", "O ar limpo", "Um vidro transparente", "Um plástico transparente"],
                0, "A madeira não deixa a luz atravessar como os materiais transparentes."),
            criarPergunta(142, "vento",
                "Uma pequena vela é empurrada pelo vento. Que efeito vemos?",
                ["Movimento da vela", "Fabricação de gelo", "Formação de uma pilha", "Crescimento de carvão"],
                0, "O ar em movimento exerce força e pode mover a vela."),
            criarPergunta(143, "calor",
                "Para uma poça de água virar gelo, ela precisa ficar como?",
                ["Recebendo calor sem parar", "Quente como uma panela no fogo", "Fria o bastante", "Cada vez mais quente"],
                2, "Ao perder calor e esfriar o suficiente, a água pode congelar."),
            criarPergunta(144, "consumo",
                "Uma tela continua ligada enquanto a turma vai ao recreio. O que faz sentido?",
                ["Aumentar o brilho ao máximo", "Pedir para desligá-la se não for usada", "Deixar vídeos passando sem público", "Ligar mais telas vazias"],
                1, "Equipamentos ligados sem uso podem gastar energia desnecessariamente.")
        ]),

        criarBloco(4, 4, "Descobrir o motivo", [
            criarPergunta(145, "som",
                "Uma régua vibra e faz barulho ao ser tocada. O som está ligado a quê?",
                ["À vibração da régua", "À cor dos números", "Ao nome escrito nela", "À marca do caderno"],
                0, "A régua em vibração movimenta o ar e pode produzir som."),
            criarPergunta(146, "agua",
                "Uma roda-d'água parou de receber água. O que pode acontecer com seu giro?",
                ["Ela diminuir o giro e parar", "Ela girar para sempre sem energia", "Ela ficar com mais força sem receber água", "Ela começar a produzir gasolina"],
                0, "Sem a força da água, o atrito faz a roda perder movimento e parar."),
            criarPergunta(147, "eletricidade",
                "Uma batedeira transforma eletricidade principalmente em quê para misturar a massa?",
                ["Frio para congelar", "Som de música", "Luz para ler", "Movimento"],
                3, "O motor da batedeira gira as peças que misturam a massa."),
            criarPergunta(148, "solar",
                "Uma placa ficou coberta de sujeira. Por que sua produção pode cair?",
                ["O Sol para de brilhar no planeta", "Menos luz chega à placa", "A placa começa a beber água", "O vento perde sua cor"],
                1, "A sujeira pode bloquear parte da luz necessária à geração solar."),
            criarPergunta(149, "movimento",
                "Depois de empurrado, um carrinho vai parando no chão. O que ajuda a freá-lo?",
                ["O nome do brinquedo", "A sombra na parede", "A cor das rodas", "O atrito com as rodas e o chão"],
                3, "O atrito transforma parte da energia de movimento e ajuda o carrinho a parar."),
            criarPergunta(150, "biomassa",
                "Plantas novas podem crescer depois de um plantio. O que elas precisam receber?",
                ["Pilhas entre as raízes", "Fios dentro das sementes", "Água e condições adequadas de luz", "Gasolina sobre as folhas"],
                2, "Água e luz adequada ajudam as plantas a crescer e formar novos materiais vegetais."),
            criarPergunta(151, "luz",
                "Uma lupa comum tem uma lente. Sem criar luz, a lente pode mudar o quê?",
                ["O peso do planeta", "O caminho da luz", "O combustível de um carro", "A energia de uma pilha guardada"],
                1, "A lente muda o caminho da luz e pode fazer uma imagem parecer maior."),
            criarPergunta(152, "vento",
                "O vento faz as folhas de uma árvore balançarem. Que energia está aparecendo nelas?",
                ["Energia de uma tomada ligada à folha", "Energia de uma pilha na raiz", "Energia de movimento", "Energia de gasolina dentro do tronco"],
                2, "O vento transfere parte de sua energia para o movimento das folhas.")
        ]),

        criarBloco(4, 5, "Explicar com suas palavras", [
            criarPergunta(153, "calor",
                "Uma tampa ajuda uma garrafa térmica a quê?",
                ["Criar calor sem nenhuma fonte", "Fazer gelo instantaneamente", "Diminuir a troca de calor com o ar", "Aumentar a entrada de vento"],
                2, "A tampa ajuda a reduzir a troca de calor com o ambiente."),
            criarPergunta(154, "solar",
                "O Sol aquece uma caixa escura e uma clara. Para comparar as cores, o que deve ser igual?",
                ["Somente o desenho da etiqueta", "Somente o dia da compra", "Somente o nome das caixas", "O tamanho e o material das caixas"],
                3, "Para comparar uma característica, mantemos as outras condições parecidas."),
            criarPergunta(155, "som",
                "Uma música sai de uma caixa de som. O ar ao redor faz o quê?",
                ["Vibra e leva o som", "Fica cheio de luz visível", "Transforma-se em água potável", "Vira carvão"],
                0, "As vibrações se espalham pelo ar e chegam aos ouvidos."),
            criarPergunta(156, "baterias",
                "Uma bateria está guardando energia. Isso significa que ela pode quê?",
                ["Acender qualquer aparelho para sempre", "Funcionar sempre vazia", "Produzir energia sem limite", "Fornecer energia mais tarde"],
                3, "Uma bateria pode guardar uma quantidade limitada de energia para uso posterior."),
            criarPergunta(157, "movimento",
                "Ao empurrar um carrinho de boneca, para onde vai parte da energia do corpo?",
                ["Para a cor da calçada", "Para o movimento do carrinho", "Para o desenho da roupa", "Para o nome da boneca"],
                1, "Os músculos transferem energia ao carrinho quando fazemos força para movê-lo."),
            criarPergunta(158, "agua",
                "A água passou por uma turbina. O que acontece com a água depois?",
                ["Ela vira eletricidade inteira", "Ela desaparece do planeta", "Ela continua sendo água", "Ela vira uma pilha"],
                2, "A usina aproveita energia do movimento; a água não se transforma toda em eletricidade."),
            criarPergunta(159, "vento",
                "Um cata-vento está parado dentro de uma caixa fechada. O que falta para o vento girá-lo?",
                ["Tinta nova nas pás", "Ar em movimento chegando às pás", "Um adesivo na caixa", "Um nome para o brinquedo"],
                1, "As pás precisam receber o movimento do ar para serem empurradas por ele."),
            criarPergunta(160, "eletricidade",
                "Uma campainha elétrica e uma lâmpada usam eletricidade. O que elas produzem principalmente?",
                ["Som e luz", "Comida e água", "Madeira e carvão", "Gelo e gasolina"],
                0, "A campainha produz principalmente som, e a lâmpada produz principalmente luz.")
        ])
    ]
});

// MÓDULO 5: Nossa missão de cuidar
trilhaFacil.modulos.push({
    id: "facil_m05_v1",
    nome: "Nossa missão de cuidar",
    ordem: 5,
    introducao: "Vamos usar o que aprendemos para escolher atitudes que cuidam dos recursos.",
    blocos: [
        criarBloco(5, 1, "Escolhas que ajudam", [
            criarPergunta(161, "consumo",
                "Faz Sol e há espaço para um varal. Como secar roupas sem usar eletricidade?",
                ["Em um varal aquecido eletricamente", "Na secadora elétrica", "No ciclo de secagem da máquina", "Estendidas no varal"],
                3, "O varal permite aproveitar o ar e o Sol para secar a roupa sem secadora."),
            criarPergunta(162, "vento",
                "Antes de instalar torres eólicas, é importante observar quais animais do lugar?",
                ["Só animais de brinquedo", "Só peixes do aquário da escola", "Só animais desenhados em livros", "Aves e morcegos"],
                3, "A escolha do local deve considerar animais que podem ser afetados pelas torres."),
            criarPergunta(163, "eletricidade",
                "Uma placa solar fornece eletricidade a um ventilador. O que o ventilador faz com ela?",
                ["Movimenta suas pás", "Fabrica novas placas", "Guarda água do rio", "Faz o Sol nascer"],
                0, "O motor do ventilador usa a eletricidade para criar movimento."),
            criarPergunta(164, "biomassa",
                "A escola vai separar restos de alimentos para reaproveitamento. Qual resto vai nesse grupo?",
                ["Lata de alumínio", "Garrafa de vidro", "Casca de laranja", "Pedaço de ferro"],
                2, "A casca de laranja é um resto vegetal que pode ter reaproveitamento adequado."),
            criarPergunta(165, "solar",
                "A placa solar no telhado precisa de cuidados. Quem deve fazer a manutenção?",
                ["Um profissional preparado", "Um colega sem orientação", "Qualquer pessoa sem conhecer o equipamento", "Uma criança sozinha"],
                0, "Manutenção em telhados e equipamentos deve ser feita por pessoas preparadas."),
            criarPergunta(166, "agua",
                "Qual atitude ajuda a cuidar dos rios usados pelas pessoas e pela natureza?",
                ["Jogar embalagens na correnteza", "Destinar o lixo à coleta adequada", "Deixar lixo na margem", "Despejar óleo no rio"],
                1, "O lixo e o óleo podem prejudicar a água e a vida no rio."),
            criarPergunta(167, "baterias",
                "Um brinquedo aceita pilhas recarregáveis. Qual é uma vantagem delas?",
                ["Devem ir para o rio após o uso", "Podem ser recarregadas e usadas novamente", "Nunca precisam receber energia", "Podem ser abertas pela criança"],
                1, "Usar pilhas recarregáveis adequadas pode diminuir o descarte de pilhas."),
            criarPergunta(168, "calor",
                "O ar-condicionado está resfriando a sala. Qual atitude evita a entrada contínua de ar quente?",
                ["Ligar um aquecedor junto", "Deixar a porta sempre aberta", "Manter a porta fechada", "Abrir todas as janelas"],
                2, "Fechar a porta ajuda a manter o ambiente que está sendo resfriado.")
        ]),

        criarBloco(5, 2, "Aproveitar melhor", [
            criarPergunta(169, "fosseis",
                "Um carro queima gasolina no motor. Além de movimento, ele pode produzir o quê?",
                ["Água potável para beber", "Vento sem nenhum gás da queima", "Luz do Sol para as plantas", "Gases que saem pelo escapamento"],
                3, "A queima de gasolina libera gases, incluindo alguns que prejudicam o ambiente."),
            criarPergunta(170, "solar",
                "Uma luminária de jardim carrega de dia e acende à noite. O que guarda a energia entre esses momentos?",
                ["Uma bateria", "Uma pedra decorativa", "Uma gota de chuva", "Uma sombra"],
                0, "A bateria pode guardar a energia produzida pela placa solar durante o dia."),
            criarPergunta(171, "movimento",
                "Para levar um carrinho ao alto de uma rampa, geralmente precisamos de quê?",
                ["Tocar uma campainha", "Apagar todas as luzes", "Fazer força para empurrá-lo", "Pintar suas rodas"],
                2, "Levar o carrinho para cima exige energia, que pode vir do nosso corpo."),
            criarPergunta(172, "consumo",
                "Um brinquedo estragou e pode ser consertado. Qual atitude aproveita melhor seus materiais?",
                ["Abandonar o brinquedo no jardim", "Pedir a um adulto para avaliar o conserto", "Comprar vários iguais imediatamente", "Jogar fora sem verificar"],
                1, "Um conserto pode prolongar a vida do brinquedo e evitar uma nova fabricação."),
            criarPergunta(173, "luz",
                "Para ler com uma luminária, onde é melhor direcionar sua luz?",
                ["Para o chão longe do livro", "Para trás de um armário", "Para a página do livro", "Para dentro de uma caixa fechada"],
                2, "Direcionar a luz para a tarefa ajuda a aproveitar melhor a iluminação."),
            criarPergunta(174, "biomassa",
                "Um combustível feito de plantas é chamado de biocombustível. Qual destes é um exemplo?",
                ["Gás natural do subsolo", "Etanol de cana", "Carvão mineral", "Gasolina de petróleo"],
                1, "O etanol de cana é produzido com uma planta e é um biocombustível."),
            criarPergunta(175, "som",
                "Uma pessoa fala ao microfone e a turma ouve nas caixas. O que as caixas produzem?",
                ["Frio para a sala", "Luz para escrever", "Calor para cozinhar", "Som mais forte"],
                3, "As caixas usam energia elétrica para produzir o som que a turma escuta."),
            criarPergunta(176, "agua",
                "Qual equipamento precisa da passagem de água para gerar movimento?",
                ["Turbina de uma hidrelétrica", "Pá de uma torre eólica", "Pilha de controle remoto", "Placa solar"],
                0, "A turbina da hidrelétrica recebe a força da água que passa por ela.")
        ]),

        criarBloco(5, 3, "Energia para todos os dias", [
            criarPergunta(177, "eletricidade",
                "Quando falta eletricidade da rede, qual destes ainda pode funcionar sem bateria?",
                ["Uma televisão de tomada", "Um ventilador de tomada", "Um apito soprado por alguém", "Um liquidificador de tomada"],
                2, "O apito aproveita o ar soprado por uma pessoa, sem depender da rede elétrica."),
            criarPergunta(178, "calor",
                "Um fogão a lenha e um elétrico têm algo em comum. O que os dois fornecem para cozinhar?",
                ["Sombra", "Calor", "Vento frio", "Gelo"],
                1, "Mesmo usando fontes diferentes, os dois podem aquecer os alimentos."),
            criarPergunta(179, "vento",
                "Uma torre eólica pode aproveitar vento durante a noite?",
                ["Sim, se houver vento adequado", "Sim, mas só queimando gasolina nas pás", "Não, o ar desaparece à noite", "Não, só existe vento com Sol"],
                0, "Pode ventar de dia ou de noite; o vento adequado permite a geração eólica."),
            criarPergunta(180, "movimento",
                "Uma pessoa move um barco usando remos. De onde vem o esforço para remar?",
                ["Do nome do rio", "Da pintura do barco", "Dos músculos da pessoa", "Da sombra do remo"],
                2, "Os músculos usam energia do corpo para mover os remos e empurrar a água."),
            criarPergunta(181, "alimentos",
                "Água é importante para o corpo. Qual destes também fornece energia como alimento?",
                ["Água com gás sem açúcar", "Gelo de água pura", "Água pura", "Banana"],
                3, "A banana fornece energia e nutrientes; a água pura hidrata, mas não fornece energia alimentar."),
            criarPergunta(182, "consumo",
                "Duas crianças querem ouvir a mesma história. Qual opção usa apenas um aparelho?",
                ["Ouvir juntas no mesmo aparelho", "Ligar dois aparelhos com a mesma história", "Ligar uma televisão em cada quarto vazio", "Deixar vários rádios ligados sem ouvir"],
                0, "Compartilhar o mesmo aparelho pode evitar o uso de outros sem necessidade."),
            criarPergunta(183, "solar",
                "Qual fonte pode ser aproveitada sem retirar combustível do chão?",
                ["Gás natural", "Petróleo", "Carvão mineral", "Luz do Sol"],
                3, "Para aproveitar a luz do Sol, não precisamos extrair um combustível do subsolo."),
            criarPergunta(184, "biomassa",
                "A madeira vem de plantas. Sua queima pode produzir fumaça?",
                ["Não, a queima faz a madeira crescer", "Sim, a queima pode produzir fumaça", "Não, plantas nunca liberam fumaça", "Não, a madeira sempre vira gelo"],
                1, "Ter origem vegetal não significa que a queima seja livre de fumaça ou de impactos.")
        ]),

        criarBloco(5, 4, "Pensar antes de agir", [
            criarPergunta(185, "calor",
                "Por que um cobertor ajuda a nos manter aquecidos?",
                ["Cria calor sem nenhuma fonte", "Fabrica fogo dentro do tecido", "Dificulta a saída do calor do corpo", "Recebe gasolina das costuras"],
                2, "O cobertor comum ajuda a conservar parte do calor que nosso corpo produz."),
            criarPergunta(186, "baterias",
                "Dois carrinhos andam: um a pilha e outro empurrado. Qual usa energia da pilha?",
                ["O carrinho empurrado", "O carrinho a pilha", "Os dois precisam de pilha", "Nenhum pode usar energia"],
                1, "O carrinho a pilha recebe energia dela; o empurrado recebe energia da pessoa."),
            criarPergunta(187, "agua",
                "Uma bomba leva água para uma caixa no alto. O que ela precisa receber para funcionar?",
                ["Tinta azul", "Areia seca", "Um desenho de rio", "Energia"],
                3, "A bomba precisa de energia para fazer a água subir."),
            criarPergunta(188, "luz",
                "O quarto está claro porque a janela recebe luz do dia. Qual fonte está ajudando?",
                ["O gás do fogão", "O Sol", "O barulho da rua", "O motor da geladeira"],
                1, "A luz natural que entra pela janela vem do Sol."),
            criarPergunta(189, "movimento",
                "Ao descer um escorregador, a criança se movimenta para baixo. O que a puxa?",
                ["A gravidade", "A cor do brinquedo", "O barulho da praça", "O nome do parque"],
                0, "A gravidade puxa os corpos para baixo e participa do movimento na descida."),
            criarPergunta(190, "mar",
                "Ondas balançam a superfície; marés mudam o nível do mar. As duas envolvem o quê?",
                ["Movimento da água", "Movimento de um fio", "Queima de carvão", "Carga de pilhas"],
                0, "Ondas e marés são movimentos diferentes da água que podem fornecer energia."),
            criarPergunta(191, "solar",
                "Faz frio, mas há bastante luz do Sol. Uma placa solar elétrica pode funcionar?",
                ["Não, porque precisa de chuva quente", "Não, porque só usa calor do ar", "Sim, mas somente se queimar lenha", "Sim, porque aproveita a luz"],
                3, "Uma placa solar elétrica aproveita luz; um dia frio também pode ser ensolarado."),
            criarPergunta(192, "vento",
                "Um muro alto bloqueia o vento de um cata-vento. O que pode acontecer?",
                ["O cata-vento produzir água", "O cata-vento virar uma pilha", "O cata-vento girar menos", "O cata-vento receber mais Sol por isso"],
                2, "Um obstáculo pode diminuir o vento que chega às pás.")
        ]),

        criarBloco(5, 5, "Missão da energia", [
            criarPergunta(193, "eletricidade",
                "De onde a tomada recebe eletricidade para um aparelho funcionar?",
                ["Da tinta da parede", "Do formato dos furos", "Da instalação elétrica ligada a uma fonte de energia", "Do barulho do aparelho"],
                2, "A tomada é um ponto de ligação; ela não cria energia sozinha."),
            criarPergunta(194, "movimento",
                "Uma bola de borracha cai e volta a subir após bater no chão. O que ela fez?",
                ["Quicou", "Evaporou", "Congelou", "Derreteu"],
                0, "A bola se deforma ao bater e devolve parte dessa energia ao quicar."),
            criarPergunta(195, "calor",
                "Misturamos água fria e morna, sem aquecer por fora. Como a mistura tende a ficar?",
                ["Com temperatura entre as duas", "Mais fria que as duas", "Mais quente que as duas", "Congelada na hora"],
                0, "A água morna perde calor e a fria recebe calor, formando uma mistura entre as duas temperaturas."),
            criarPergunta(196, "biomassa",
                "Óleo de cozinha usado pode ser reaproveitado. O que fazer com ele?",
                ["Despejar na pia", "Espalhar na terra", "Pedir a um adulto para encaminhar à coleta adequada", "Jogar no rio"],
                2, "A coleta adequada permite reaproveitamentos, inclusive a produção de certos combustíveis."),
            criarPergunta(197, "agua",
                "Qual dupla move as máquinas de uma hidrelétrica e de uma torre eólica?",
                ["Sol e areia", "Vento e gasolina", "Carvão e pilhas", "Água e vento"],
                3, "A água movimenta a turbina da hidrelétrica; o vento movimenta as pás da torre eólica."),
            criarPergunta(198, "som",
                "Um carrinho a pilha anda e faz barulho. Quais efeitos mostram o uso de energia?",
                ["Só mudança de nome", "Movimento e som", "Só aumento de tamanho", "Só mudança de cor"],
                1, "A energia pode aparecer em mais de um efeito, como movimento e som."),
            criarPergunta(199, "solar",
                "Placas solares também precisam ser fabricadas. Essa fabricação usa recursos?",
                ["Não, as placas crescem como folhas", "Sim, usa materiais e energia", "Não, as placas nascem prontas", "Não, o Sol monta as placas sozinho"],
                1, "Mesmo fontes renováveis precisam de equipamentos que usam materiais e energia na fabricação."),
            criarPergunta(200, "consumo",
                "A televisão parece desligada, mas uma luzinha continua acesa. Ela pode gastar energia?",
                ["Não, a tomada passa a fabricar vento", "Não, uma luz acesa nunca usa energia", "Não, a televisão começa a se recarregar com som", "Sim, pode estar em modo de espera"],
                3, "Alguns aparelhos continuam usando uma pequena quantidade de energia no modo de espera.")
        ])
    ]
});

module.exports = trilhaFacil;